version: "3.7"

networks:
  dt_api:

volumes:
  wss_mongo:
    driver: local

services:
  go:
    build:
      context: ./ws
      target: prod
    depends_on:
      - redis
      - mongo
    ports:
      - "8080:8000"

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
    volumes:
      - wss_mongo:/data/db

  redis:
    image: redis:6.2-alpine
    restart: always
    command: redis-server --requirepass $REDIS_PASS
